# Generated by Django 3.2.4 on 2023-11-22 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='owner_name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('master_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.master')),
            ],
        ),
    ]
